---
title: "Generate synthetic nucleosome maps"
output:
  BiocStyle::html_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{Generate synthetic nucleosome maps}
  %\VignettePackage{shinyNucleoSim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r style, echo = FALSE, results = 'asis', message = FALSE}
BiocStyle::markdown()
library(knitr)
```

<br>
**Package**: `r Rpackage("shinyNucleoSim")`<br />
**Authors**: `r packageDescription("shinyNucleoSim")[["Author"]]`<br />
**Version**: `r packageDescription("shinyNucleoSim")$Version`<br />
**Compiled date**: `r Sys.Date()`<br />
**License**: `r packageDescription("shinyNucleoSim")[["License"]]`<br />
  
# Licensing and citing
  
This package and the underlying `r Rpackage("shinyNucleoSim")` code are 
distributed under the Artistic license 2.0. You are free to use and 
redistribute this software.

If you use this package for a publication, we would ask you to cite the 
following:

# Introduction

The first human genome was released in 2003 at a cost of 2.7 billion dollars.
The development of next-generation sequencing (NGS) technologies have
dramatically decreased the cost of genomics studies. NGS can be applied to a
wide range of studies, such as genomic, metagenomic and epigenetic and is now
commondly used. 

The initial goal fo data simulators was to generate data for software testing.


# Acknowledgements

The `r Rpackage("shinyNucleoSim")` application is based on the package 
`r Biocpkg("shinyNucleoSim")`, available at Bioconductor at this 
address [http://bioconductor.org/packages/nucleoSim/](http://bioconductor.org/packages/nucleoSim/).

  
  